printf "mv_eth," && less mv_eth_n2_p8_2000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "mv_eth," && less mv_eth_n2_p8_4000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "mv_eth," && less mv_eth_n2_p8_6000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "mv_eth," && less mv_eth_n2_p8_8000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "mv_eth," && less mv_eth_n2_p8_10000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "mv_ib," && less mv_ib_n2_p8_2000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "mv_ib," && less mv_ib_n2_p8_4000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "mv_ib," && less mv_ib_n2_p8_6000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "mv_ib," && less mv_ib_n2_p8_8000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "mv_ib," && less mv_ib_n2_p8_10000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "mv_n1," && less mv_n1_p8_2000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "mv_n1," && less mv_n1_p8_4000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "mv_n1," && less mv_n1_p8_6000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "mv_n1," && less mv_n1_p8_8000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "mv_n1," && less mv_n1_p8_10000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_ib," && less op_opt_n2_p8_2000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_ib," && less op_opt_n2_p8_4000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_ib," && less op_opt_n2_p8_6000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_ib," && less op_opt_n2_p8_8000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_ib," && less op_opt_n2_p8_10000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_eth," && less op_opt_eth_n2_p8_2000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_eth," && less op_opt_eth_n2_p8_4000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_eth," && less op_opt_eth_n2_p8_6000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_eth," && less op_opt_eth_n2_p8_8000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_eth," && less op_opt_eth_n2_p8_10000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_n1," && less op_opt_n1_p8_2000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_n1," && less op_opt_n1_p8_4000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_n1," && less op_opt_n1_p8_6000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_n1," && less op_opt_n1_p8_8000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
printf "op_n1," && less op_opt_n1_p8_10000 | grep "start of sending C" | cut -d " " -f 9 | sort -r | tail -n 1
