printf "mv_eth," && less mv_eth_n2_p16_2000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "mv_eth," && less mv_eth_n2_p16_4000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "mv_eth," && less mv_eth_n2_p16_6000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "mv_eth," && less mv_eth_n2_p16_8000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "mv_eth," && less mv_eth_n2_p16_10000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "mv_ib," && less mv_ib_n2_p16_2000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "mv_ib," && less mv_ib_n2_p16_4000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "mv_ib," && less mv_ib_n2_p16_6000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "mv_ib," && less mv_ib_n2_p16_8000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "mv_ib," && less mv_ib_n2_p16_10000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "mv_n1," && less mv_n1_p16_2000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "mv_n1," && less mv_n1_p16_4000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "mv_n1," && less mv_n1_p16_6000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "mv_n1," && less mv_n1_p16_8000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "mv_n1," && less mv_n1_p16_10000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_ib," && less op_opt_n2_p16_2000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_ib," && less op_opt_n2_p16_4000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_ib," && less op_opt_n2_p16_6000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_ib," && less op_opt_n2_p16_8000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_ib," && less op_opt_n2_p16_10000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_eth," && less op_opt_eth_n2_p16_2000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_eth," && less op_opt_eth_n2_p16_4000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_eth," && less op_opt_eth_n2_p16_6000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_eth," && less op_opt_eth_n2_p16_8000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_eth," && less op_opt_eth_n2_p16_10000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_n1," && less op_opt_n1_p16_2000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_n1," && less op_opt_n1_p16_4000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_n1," && less op_opt_n1_p16_6000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_n1," && less op_opt_n1_p16_8000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
printf "op_n1," && less op_opt_n1_p16_10000 |grep "end of reception of A" | cut -f 10 -d " " | sort -n| tail -n 1
